# 服务参数
server:
  port: 8090

# 应用名称
spring:
  application:
    name: spring-boot-poi-easyexcel
  # json format
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # file upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      file-size-threshold: 2KB
      max-request-size: 10MB